# Generated by Django 3.1.7 on 2021-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210313_1457'),
        ('users', '0002_remove_profile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review',
            field=models.ManyToManyField(related_name='review', to='reviews.Reviews'),
        ),
    ]
