# Generated by Django 3.1.7 on 2021-03-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda'), ('Sudan', 'Sudan'), ('Somalia', 'Somalia')], default='select country', max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Murang', 'Murang'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], default='Nairobi', max_length=200)),
                ('postal_code', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('make', models.CharField(choices=[('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Jeep', 'Jeep'), ('Rolls Royce', 'Rolls Royce'), ('Mercedes Benz', 'Mercedes Benz'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Porsche', 'Porsche'), ('BMW', 'Subaru'), ('Acura', 'Acura')], default='Tesla', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('odometer', models.CharField(max_length=300)),
                ('colour', models.CharField(max_length=50)),
                ('mpg', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=200)),
                ('market_value', models.CharField(max_length=300)),
                ('vin', models.CharField(max_length=17)),
                ('license_plate', models.CharField(max_length=30)),
                ('price_per_day', models.IntegerField()),
                ('car_details', models.TextField()),
                ('description', models.TextField()),
                ('as_from', models.DateField()),
                ('to', models.DateField()),
                ('guideline', models.TextField(max_length=300)),
                ('safety_and_quality_standards', models.BooleanField()),
                ('usb_charger', models.BooleanField(default=False)),
                ('gps', models.BooleanField()),
                ('automatic', models.BooleanField()),
                ('sunroof', models.BooleanField()),
                ('apple_car_play', models.BooleanField()),
                ('all_wheel_drive', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('audio_input', models.BooleanField()),
                ('convertible', models.BooleanField()),
                ('child_seat', models.BooleanField()),
                ('longterm_car', models.BooleanField()),
                ('bike_rack', models.BooleanField()),
                ('profile_photo', models.ImageField(upload_to='profiles')),
                ('mobile_number', models.IntegerField()),
                ('drivers_license', models.CharField(max_length=200)),
                ('your_goals', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cars',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(choices=[('Car', 'Car'), ('classics', 'classics'), ('convertibles', 'convertibles'), ('Exotic & Luxury', 'Exotic & Luxury'), ('Minivans', 'Minivans'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('Trucks', 'Trucks'), ('Vans', 'Vans')], default='Car', max_length=100)),
                ('cat_image', models.ImageField(upload_to='categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='car_photos')),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.cars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='car_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category'),
        ),
    ]
