# Generated by Django 3.1.7 on 2021-03-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cars_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='owner',
        ),
    ]
