# Generated by Django 3.1.7 on 2021-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_cars_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(choices=[('Tesla', 'Tesla'), ('Lamborghini', 'Lamborghini'), ('Jeep', 'Jeep'), ('Rolls Royce', 'Rolls Royce'), ('Mercedes Benz', 'Mercedes Benz'), ('Ferrari', 'Ferrari'), ('Maserati', 'Maserati'), ('Porsche', 'Porsche'), ('BMW', 'Subaru'), ('Acura', 'Acura'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai'), ('Apple', 'Apple'), ('Subaru', 'Subaru')], default='Tesla', max_length=100),
        ),
    ]
