# Generated by Django 3.2 on 2022-01-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210315_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cars',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='as_from',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='guideline',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='market_value',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='odometer',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='safety_and_quality_standards',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='to',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='your_goals',
        ),
    ]
